# dev开发环境

# mysql - local - url
spring:
  application:
    name: mall-api
  cloud:
      consul:
        host: ${CONSUL}
        port: ${CONSUL_PORT}
        discovery:
          register: false
  redis:
    host: ${REDIS}
    port: ${REDIS_PORT}
    password: ${REDIS_PWD}
    soTimeout: 2000
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms
    expire-time: 60
  rabbitmq:
      host: ${MQ}
      port: ${MQ_PORT}
      username: ${MQ_USER}
      password: ${MQ_PWD}
      publisher-confirms: true

ucapi:
    service-name: uc
    app-id: platform_app
    secret: 1ArLkQgVaWUYFPHv7NwzkpudzDFsfsaQ
    pool-max-total: 50
    pool-block-when-exhausted: true
    pool-max-wait-millis: -1
    pool-min-evictable-idle-time-millis: 600000
    pool-max-idle: 10
    pool-min-idle: 0

seaweed:
  ip: ${SEAWEED}
  port: ${SEAWEED_PORT}

server:
  port: 7077
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8
