# dev开发环境
grpc:
  server:
    port: 9091
    address: 172.28.3.9

# mysql - local - url
spring:
  application:
    name: cj-scores
  datasource:
          name: dev
#          url: jdbc:mysql://127.0.0.1:3306/cj_scores?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#          username: root
#          password: root
          url: jdbc:mysql://172.28.3.45:20010/cj_point?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: cj_point
          password: 123
#          url: jdbc:mysql://47.100.222.71:3306/cj_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#          username: m_match
#          password: YEMINHE2du0xYBna
#           使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 1000
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
  cloud:
      consul:
        host: 172.28.3.45
        port: 8500
        discovery:
          register: false
  redis:
    host: 127.0.0.1
    port: 6379
    soTimeout: 2000
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms
    expire-time: 3600



# server config
server:
  port: 9001
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8
# uc-api module config
ucapi:
    service-name: uc
    app-id: platform_app
    secret: 1ArLkQgVaWUYFPHv7NwzkpudzDFsfsaQ
    pool-max-total: 50
    pool-block-when-exhausted: true
    pool-max-wait-millis: -1
    pool-min-evictable-idle-time-millis: 600000
    pool-max-idle: 10
    pool-min-idle: 0