# dev开发环境
# mysql - local - url
spring:
  application:
    name: cj-push
  cloud:
      consul:
        host: 172.28.3.45
        port: 8500
        discovery:
          register: true
  redis:
    host: 127.0.0.1
    port: 6379
    expire-time: 3600
    soTimeout: 2000
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms

# server config
server:
  port: 8088
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8


mongo:
  address: localhost:27017
#  replica-set:
  database: admin
  username: root
  password: root
  options.min-connections-per-host: 30
  options.max-connections-per-host: 30
  options.threads-allowed-to-block-for-connection-multiplier: 5
  options.server-selection-timeout: 30000
  options.max-wait-time: 120000
  options.max-connection-idel-time: 0
  options.max-connection-life-time: 0
  options.connect-timeout: 10000
  options.socket-timeout: 0
  options.socket-keep-alive: false
  options.ssl-enabled: false
  options.ssl-invalid-host-name-allowed: false
  options.always-use-m-beans: false
  options.heartbeat-socket-timeout: 20000
  options.heartbeat-connect-timeout: 20000
  options.min-heartbeat-frequency: 500
  options.heartbeat-frequency: 10000
  options.local-threshold: 15


jiguang:
  appkey: 928c19fc99d990c03efee5ea
  masterSecret: 5c387bd797238429baba2fbd