# spring-boot-webapi moudule 通用配置
# create 2018-03-22

#active {profile}
spring:
  profiles:
    active: @profileActive@
  aop:
    proxy-target-class: true
  cache:
    type: redis
  servlet:
    multipart:
      maxFileSize: 20Mb
      maxRequestSize: 20Mb

#配置springcloud feign请求处理的超时时间
ribbon:
  ReadTimeout: 120000
 #请求连接的超时时间
  ConnectTimeout: 60000

management:
  endpoints:
    enabled: false
  metrics:
    enabled: true
    sensitive: false
    path: /ep/metrics
  info:
    enabled: true
    sensitive: false
    path: /ep/info
  heapdump:
    enabled: true
    sensitive: false
    path: /ep/heapdump
  trace:
    enabled: true
    sensitive: false
    path: /ep/trace
  health:
    enabled: true
    sensitive: false



